spring:
  application:
    name: auth-service
  cache:
    cache-names:
      - "users"
    redis:
      time-to-live: 10m

    type: redis
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  tomcat:
    basedir: /app/tomcat-temp
