global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080'] # Assuming 8080

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080'] # Assuming 8080

  - job_name: 'workspace-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['workspace-service:8080'] # Assuming 8080

  - job_name: 'page-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['page-service:8080'] # Assuming 8080

  - job_name: 'collaboration-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['collaboration-service:9091']
