spring:
  application:
    name: workspace-service
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
  threads:
    virtual:
      enabled: true
server:
  tomcat:
    basedir: /app/tomcat-temp
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.dj.ckw.workspaceservice: info
  structured:
    format:
      console: logstash
